[build]
builder = "dockerfile"
dockerfilePath = "apps/cms/Dockerfile"

[deploy]
healthcheckPath = "/_health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
